server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: "/var/log/**/log*.log"
    pipeline_stages:
      - match:
          selector: '{job="varlogs"}'
          stages:
            - regex:
                expression: '^(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3})\s(?P<service>(\S+))\s+(?P<log_level>(\S+))\s(\d+)\s+---\s\[(\S+)\]\s+(\S+)\s+:(?P<message>(.*))$'
            - labels:
                log_level:
                service: